### ISSUE TITLE
import pyglet_ffmpeg2 results in Permission denied

### ISSUE THREAD

**Issue by bjourne** [pythonarcade/pyglet-ffmpeg#5]
See the traceback:
```
>>> import pyglet_ffmpeg2
Start
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/pyglet_ffmpeg2/__init__.py", line 5, in <module>
    load_ffmpeg()
  File "/usr/lib/python3.7/site-packages/pyglet_ffmpeg2/loader.py", line 17, in load_ffmpeg
    _locate_binaries()
  File "/usr/lib/python3.7/site-packages/pyglet_ffmpeg2/loader.py", line 56, in _locate_binaries
    _ensure_linux_symlinks(path)
  File "/usr/lib/python3.7/site-packages/pyglet_ffmpeg2/loader.py", line 93, in _ensure_linux_symlinks
    os.path.join(bin_folder, symlink)
PermissionError: [Errno 13] Permission denied: '/usr/lib64/python3.7/site-packages/pyglet_ffmpeg2/linux_x86_64/libavcodec.so.58.21.104' -> '/usr/lib64/python3.7/site-packages/pyglet_ffmpeg2/linux_x86_64/libavcodec.so.58'
```

**Comment by bjourne** [comment]
The workaround is to install pyglet_ffmpeg2 in a writable location, but then I get lots of `Unable to find match for ffmpeg sound library at expected location:` errors instead.

**Comment by benmoran56** [comment]
Looks like if installing in a local location, such as with "pip install --user", the lib path should be "lib" instead of "lib64".
